"""Generate synthetic sample option chains for demos and tests.

The chains are NOT real quotes. Prices come from Black-Scholes with a simple
volatility skew, plus a bid/ask spread and made-up open interest, so every
number is internally consistent (bid < mid < ask, delta matches IV, etc.).

    python examples/make_sample_chains.py            # writes examples/chains/*.json
"""

from __future__ import annotations

import json
import math
import sys
from datetime import date, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from thetadesk import pricing  # noqa: E402

AS_OF = date(2026, 9, 11)

# symbol -> (spot, at-the-money IV, iv_rank, earnings_date, strike step)
UNIVERSE = {
    "NBIS": (61.40, 0.92, 58.0, "2026-11-12", 2.5),
    "META": (742.10, 0.34, 31.0, "2026-10-28", 10.0),
    "HOOD": (118.25, 0.66, 47.0, "2026-11-04", 5.0),
}
EXPIRIES = [AS_OF + timedelta(days=d) for d in (7, 21, 35, 49, 77)]


def _skewed_iv(atm_iv: float, moneyness: float) -> float:
    """Puts trade richer than calls: IV rises as strikes move below spot."""
    return atm_iv * (1.0 + 0.35 * max(-moneyness, 0.0) + 0.10 * max(moneyness, 0.0))


def build_chain(symbol: str) -> dict:
    spot, atm_iv, iv_rank, earnings, step = UNIVERSE[symbol]
    options = []
    low = math.floor(spot * 0.70 / step) * step
    high = math.ceil(spot * 1.30 / step) * step
    strike = low
    while strike <= high:
        moneyness = math.log(strike / spot)
        iv = _skewed_iv(atm_iv, moneyness)
        for expiry in EXPIRIES:
            t = pricing.years((expiry - AS_OF).days)
            for right in ("put", "call"):
                mid = pricing.bs_price(spot, strike, iv, t, right)
                if mid < 0.03:
                    continue
                half = max(0.02, mid * 0.04)
                bid = round(max(mid - half, 0.01), 2)
                ask = round(mid + half, 2)
                delta = pricing.greeks(spot, strike, iv, t, right).delta
                distance = abs(moneyness) / max(atm_iv, 0.1)
                oi = int(3000 * math.exp(-1.5 * distance)) + 40
                vol = int(oi * 0.18)
                options.append(
                    {
                        "expiry": expiry.isoformat(),
                        "strike": round(strike, 2),
                        "right": right,
                        "bid": bid,
                        "ask": ask,
                        "iv": round(iv, 4),
                        "delta": round(delta, 4),
                        "open_interest": oi,
                        "volume": vol,
                    }
                )
        strike += step
    return {
        "underlying": symbol,
        "spot": spot,
        "as_of": AS_OF.isoformat(),
        "earnings_date": earnings,
        "iv_rank": iv_rank,
        "note": "SYNTHETIC sample data generated by examples/make_sample_chains.py; not real quotes.",
        "options": options,
    }


def main() -> None:
    out_dir = Path(__file__).resolve().parent / "chains"
    out_dir.mkdir(exist_ok=True)
    for symbol in UNIVERSE:
        chain = build_chain(symbol)
        path = out_dir / f"{symbol}.json"
        path.write_text(json.dumps(chain, indent=1) + "\n")
        print(f"wrote {path} ({len(chain['options'])} options)")


if __name__ == "__main__":
    main()
